CC=g++
CFLAGS=-c -Wall -MMD 
LDFLAGS=

SOURCES=parser.cpp
OBJECTS=$(SOURCES:.cpp=.o)
DEPS=$(SOURCES:.cpp=.d)
EXECUTABLE=createDb

SOURCES_CLIENT=ip2country.cpp
OBJECTS_CLIENT=$(SOURCES_CLIENT:.cpp=.o)
DEPS_CLIENT=$(SOURCES_CLIENT:.cpp=.d)
EXECUTABLE_CLIENT=ip2country

-include $(DEPS)
-include $(DEPS_CLIENT)

all: $(SOURCES) $(EXECUTABLE) $(SOURCES_CLIENT) $(EXECUTABLE_CLIENT)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

$(EXECUTABLE_CLIENT): $(OBJECTS_CLIENT) 
	$(CC) $(LDFLAGS) $(OBJECTS_CLIENT) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
	
clean: 
	rm -rf $(OBJECTS) $(EXECUTABLE) $(OBJECTS_CLIENT) $(EXECUTABLE_CLIENT) $(DEPS) $(DEPS_CLIENT)
